"""
Emit everything the static site needs, into web/.

    python -m src.export.site_data

The site has to work when index.html is opened straight off the filesystem,
with no server. That rules out `fetch()` and ES-module imports, both of which
browsers block for file:// URLs. So every data file is written twice:

  * `web/data/<name>.json` -- the canonical artefact, readable by anything;
  * `web/data/<name>.js`   -- the same content assigned onto window.EGUN_DATA,
                              loaded with a plain <script> tag, which file://
                              does allow.

The .js files are generated, never hand-edited. The .json files are the ones to
read or reuse.

Nothing here invents data. `dataset.json` is a faithful serialisation of
data/processed/dataset_master.csv, every row carrying the provenance columns it
already has, so the Dataset tab can show where each gun came from.
"""

import json
import os
import shutil

import pandas as pd

from ..ann import dataset as ds

NUMERIC = [
    "perveance_uperv", "rw_mm", "C", "theta_cone_deg", "theta_ann_panahi_deg",
    "theta_iterative_deg", "theta_noniterative_deg", "theta_modified_noniter_deg",
    "rc_mm", "Rc_mm", "generator_mre_pct",
]

FIGURES = [
    "fig3_regression_train.png", "fig3_regression_test.png",
    "fig4_mse_vs_epochs.png", "fig5_method_comparison.png",
    "fig6_percentage_error.png", "fig7_restart_histogram.png",
    "tier_overlap.png",
]


def write_pair(web_dir, name, payload, js_key):
    """Write data/<name>.json and the <script>-loadable data/<name>.js beside it."""
    data_dir = os.path.join(web_dir, "data")
    os.makedirs(data_dir, exist_ok=True)

    json_path = os.path.join(data_dir, name + ".json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)

    js_path = os.path.join(data_dir, name + ".js")
    with open(js_path, "w", encoding="utf-8") as f:
        f.write("/* GENERATED by src/export/site_data.py -- do not edit.\n"
                "   Mirrors %s.json as a plain script, because browsers block\n"
                "   fetch() and module imports on file:// URLs. */\n" % name)
        f.write("window.EGUN_DATA = window.EGUN_DATA || {};\n")
        f.write("window.EGUN_DATA.%s = " % js_key)
        json.dump(payload, f, separators=(",", ":"))
        f.write(";\n")

    print(f"  {json_path}")
    print(f"  {js_path}")
    return json_path


def build_dataset(df):
    """Every row, with provenance, as plain JSON records."""
    rows = []
    for _, r in df.iterrows():
        row = {}
        for col in df.columns:
            v = r[col]
            if col in NUMERIC:
                row[col] = None if pd.isna(v) else float(v)
            elif col == "source_case_id":
                # Synthetic rows have no case id: case ids identify published
                # guns, and inventing one for a generated row would be the exact
                # confusion this dataset is built to prevent.
                row[col] = None if pd.isna(v) or v == "" else int(v)
            else:
                row[col] = None if pd.isna(v) else str(v)
        rows.append(row)

    n_a = int((df["tier"] == "A_literature").sum())
    n_b = int((df["tier"] == "B_synthetic").sum())

    return {
        "generated_from": "data/processed/dataset_master.csv",
        "n_rows": len(rows),
        "columns": list(df.columns),
        "rows": rows,
        "provenance": {
            "tier_a_rows": n_a,
            "tier_b_rows": n_b,
            "tier_c_rows": 0,
            # The one sentence the Dataset tab must never let a visitor miss.
            "headline": (
                f"{len(rows)} rows - {n_a} from published tables, "
                f"{n_b} generated by a validated physics model."
            ),
            "real_vs_generated": {
                "real": n_a,
                "generated": n_b,
                "plain_language": (
                    f"Only {n_a} of these {len(rows)} rows describe guns that were "
                    f"actually built and measured. The other {n_b} are output from "
                    f"a physics model, computed at design points nobody has "
                    f"published a gun for. They are useful for training and they "
                    f"are not measurements."
                ),
            },
            "generator": {
                "envelope": "C >= 8",
                "mre_pct": 2.80,
                "mae_deg": 0.85,
                "n_validation_cases": 23,
                "leave_one_out_mre_pct": 2.89,
                "strict_gate_failed": True,
                "strict_gate_numbers": "1.66 deg / 5.75 % over all 30 cases",
                "excluded_cases": [4, 7, 10, 18, 19, 27, 28],
                "plain_language": (
                    "The physics model behind the synthetic rows was checked "
                    "against 30 real guns. Over the whole range it is off by "
                    "5.75 % on average, which is not good enough. Restricted to "
                    "convergence ratios of 8 or more it is off by 2.80 %, which "
                    "is better than the 3.74 % the reference paper's own network "
                    "achieves - so synthetic rows were generated only there. "
                    "Seven real guns sit below that cut-off and have no "
                    "synthetic support at all."
                ),
            },
            "source_papers": sorted(set(df["source_key"])),
            "upstream_references": 3,
            "beam_types": sorted(set(df["beam_type"])),
            "split": {
                "train": int((df["split"] == "train").sum()),
                "test": int((df["split"] == "test").sum()),
                "real_train": int(((df["split"] == "train") &
                                   (df["tier"] == "A_literature")).sum()),
                "synthetic_train": int(((df["split"] == "train") &
                                        (df["tier"] == "B_synthetic")).sum()),
                "test_is_all_real": bool(
                    (df.loc[df["split"] == "test", "tier"] == "A_literature").all()),
                "test_cases": sorted(
                    int(c) for c in df.loc[df["paper_split"] == "test", "source_case_id"]
                ),
            },
            "tier_b_note": (
                "Tier B rows are physics-model output, not measurements. The model "
                "was validated against the 30 published guns and reaches "
                "MAE 0.85 deg / MRE 2.80 % over convergence ratios C >= 8, which "
                "is the only region rows were generated in. Over the full range it "
                "manages only 1.66 deg / 5.75 % and fails the project's strict "
                "gate - so the seven real guns with C < 8 are excluded and have no "
                "synthetic support. No synthetic row is ever used as a test row."
            ),
            "correction_note": (
                "Case 11 was recorded as theta = 37.4 in our original working "
                "sheet; Table 2 prints 37.04. A digit transposition, found by "
                "checking every row against the PDF, corrected in this dataset. "
                "The original sheet is kept unmodified at "
                "data/raw/ann_testing_original.csv."
            ),
            "derived_note": (
                "rc_mm = sqrt(C) * r_w is the cathode disc radius; Rc_mm = "
                "rc_mm / sin(theta) is the radius of curvature of the spherical "
                "cap. Both are exact algebra from eqs (2) and (4), flagged in "
                "derived_fields. Every other column is read from the paper."
            ),
        },
    }


def build_lb_table(n=1501, gamma_max=3.0):
    """
    The Langmuir-Blodgett alpha function, tabulated for the browser.

    alpha solves  3*a*a'' + a'^2 + 3*a*a' = 1,  a(0)=0, a'(0)=1, derived from
    Poisson's equation for spherically convergent space-charge-limited flow. Our
    integration of it reproduces the classical series to ~1e-9, and it is the one
    piece of the physics engine that passed its check (D4) -- the aperture-lens
    closure is what failed.

    A table rather than a series because the classical series diverges well
    before gamma = 3, and a table straight off the verified ODE cannot drift
    away from the Python implementation the way a re-derived series could.

    The gun drawing uses it to place the anode: given theta and P,
        alpha(gamma)^2 = 29.33 * (1 - cos theta) / P,
    solved for gamma = ln(Rc/Ra).
    """
    import numpy as np
    from ..physics.probe_closure import alpha_and_deriv

    gammas = np.linspace(0.0, gamma_max, n)
    alphas = [0.0]
    for g in gammas[1:]:
        a, _ = alpha_and_deriv(float(g))
        alphas.append(float(a))

    return {
        "note": ("alpha(gamma) for spherical space-charge-limited flow, from the "
                 "ODE 3*a*a'' + a'^2 + 3*a*a' = 1 integrated in src/physics/"
                 "probe_closure.py. Verified against the classical Langmuir-"
                 "Blodgett series to ~1e-9."),
        "equation": "P_uperv = 29.33 * (1 - cos theta) / alpha(gamma)^2",
        "gamma_min": 0.0,
        "gamma_max": float(gamma_max),
        "n": int(n),
        "alpha": [round(a, 10) for a in alphas],
    }


def build_benchmark(root):
    """The numbers the Results tab quotes, straight from the run artefacts."""
    out = {}
    for model_id, run_name in (("M1", "m1_run.json"), ("M1-multi", "m1-multi_run.json")):
        path = os.path.join(root, "reports", run_name)
        if not os.path.exists(path):
            continue
        with open(path, encoding="utf-8") as f:
            run = json.load(f)
        # Reshape the run artefact's per-split blocks into the same "selected"
        # shape the model JSON uses, so the page reads one structure rather than
        # two that happen to share a key name.
        tgts = run["config"]["targets"]
        selected = {
            "train_mre_pct": {k: run["metrics"]["train"][k]["mre_pct"] for k in tgts},
            "test_mre_pct": {k: run["metrics"]["test"][k]["mre_pct"] for k in tgts},
            "train_rmse": {k: run["metrics"]["train"][k]["rmse"] for k in tgts},
            "test_rmse": {k: run["metrics"]["test"][k]["rmse"] for k in tgts},
            "train_pearson_r": {k: run["metrics"]["train"][k]["pearson_r"] for k in tgts},
            "test_pearson_r": {k: run["metrics"]["test"][k]["pearson_r"] for k in tgts},
        }
        out[model_id] = {
            "targets": tgts,
            "n_params": run["n_params"],
            "seed": run["seed"],
            "epochs_run": run["epochs_run"],
            "metrics": {"selected": selected, "by_split": run["metrics"]},
            "test_case_ids": run["test_case_ids"],
            "predictions_test": run["predictions"]["test"],
            "truth_test": run["truth"]["test"],
            "restart_spread": run.get("restart_spread"),
        }

    exp_path = os.path.join(root, "reports", "experiments.json")
    if os.path.exists(exp_path):
        with open(exp_path, encoding="utf-8") as f:
            exp = json.load(f)
        out["distributions"] = exp.get("E5_shipped_distributions")
        out["C_scaling"] = exp.get("E4_C_scaling")
        out["residual_weights"] = exp.get("E1_residual_weights")

    out["paper"] = {
        "citation": ("R. Panahi, S.A.H. Feghhi, Sh. Sanaye Hajari, M. Khorsandi, "
                     "'Determination of the Half-Beam cone angle for Pierce electron "
                     "gun design using an artificial neural network', Results in "
                     "Physics 73 (2025) 108256"),
        "doi": "10.1016/j.rinp.2025.108256",
        "licence": "CC BY-NC",
        "train_mre_pct": 2.18, "test_mre_pct": 3.74,
        "train_rmse_deg": 0.95, "test_rmse_deg": 2.09,
        "train_pearson_r": 0.997, "test_pearson_r": 0.990,
        "recomputed_from_our_extraction": {
            "train_mre_pct": 2.1870, "test_mre_pct": 3.7437,
            "train_rmse_deg": 0.959, "test_rmse_deg": 2.093,
        },
    }
    return out


def main():
    root = ds.repo_root()
    web = os.path.join(root, "web")
    os.makedirs(web, exist_ok=True)

    print("site data -> web/")

    df = pd.read_csv(ds.default_path())
    write_pair(web, "dataset", build_dataset(df), "dataset")
    write_pair(web, "benchmark", build_benchmark(root), "benchmark")
    write_pair(web, "lb_alpha", build_lb_table(), "lbAlpha")

    # The models, copied verbatim so the site and the repo cannot drift apart.
    for src_name, js_key in (("model_m1.json", "model"),
                             ("model_m1_multi.json", "modelMulti")):
        src = os.path.join(root, "models", src_name)
        if not os.path.exists(src):
            print(f"  SKIP {src_name} (not exported yet)")
            continue
        with open(src, encoding="utf-8") as f:
            write_pair(web, os.path.splitext(src_name)[0], json.load(f), js_key)

    # Figures, so the site is self-contained and makes no network calls.
    fig_dir = os.path.join(web, "figures")
    os.makedirs(fig_dir, exist_ok=True)
    for name in FIGURES:
        src = os.path.join(root, "reports", "figures", name)
        if os.path.exists(src):
            shutil.copyfile(src, os.path.join(fig_dir, name))
            print(f"  {os.path.join(fig_dir, name)}")
        else:
            print(f"  SKIP figure {name} (not generated yet)")


if __name__ == "__main__":
    main()
