/*
 * The gun geometry, for the cross-section drawing.
 *
 * What is on firm ground here and what is not:
 *
 *  SOLID.  r_c and R_c are exact algebra from equations (2) and (4) of the
 *          paper, given theta. No approximation.
 *  SOLID.  The anode radius comes from the Langmuir-Blodgett relation
 *              P = 29.33 (1 - cos theta) / alpha(gamma)^2,   gamma = ln(Rc/Ra)
 *          solved for gamma against a table generated by our own integration of
 *          the LB ODE, which reproduces the classical series to ~1e-9. That
 *          solver is the part of the physics engine that passed its check.
 *  SKETCH. The anode-to-waist drift envelope integrates the space-charge
 *          expansion r'^2 = 2K ln(r/r_w). That is the same equation (II) whose
 *          aperture-lens closure FAILED the validation gate at MAE 1.66 deg, so
 *          the drift LENGTH should be read as indicative, not as a dimension to
 *          build to. The UI says so.
 *
 * The drawing is a schematic. It is here to make the geometry legible while a
 * slider moves, not to specify hardware.
 */
(function (root) {
  "use strict";

  var P_CONST = 29.33;      // uperv, spherical diode constant
  var K_CONST = 1.5156e-2;  // generalised perveance per uperv

  var deg = Math.PI / 180;

  /* alpha(gamma) by linear interpolation in the exported table. */
  function alphaOf(table, gamma) {
    if (!table || gamma <= 0) return 0;
    var n = table.n, gMax = table.gamma_max;
    if (gamma >= gMax) return NaN;
    var pos = (gamma / gMax) * (n - 1);
    var i = Math.floor(pos), f = pos - i;
    if (i >= n - 1) return table.alpha[n - 1];
    return table.alpha[i] * (1 - f) + table.alpha[i + 1] * f;
  }

  /*
   * Invert the LB relation for gamma. alpha is monotone increasing in gamma, so
   * a bisection on the table is enough and cannot pick a spurious branch.
   */
  function gammaFor(table, thetaDeg, P) {
    if (!table) return NaN;
    var want = (P_CONST * (1 - Math.cos(thetaDeg * deg))) / P;   // = alpha^2
    if (!isFinite(want) || want <= 0) return NaN;
    var target = Math.sqrt(want);
    if (target > table.alpha[table.n - 1]) return NaN;

    var lo = 0, hi = table.gamma_max;
    for (var it = 0; it < 60; it++) {
      var mid = 0.5 * (lo + hi);
      if (alphaOf(table, mid) < target) lo = mid; else hi = mid;
    }
    return 0.5 * (lo + hi);
  }

  /*
   * The beam envelope from the anode down to the waist.
   *
   * r'^2 = 2K ln(r/r_w) with K = 1.5156e-2 * P. Substituting r = r_w e^(u^2)
   * removes the singularity at the waist, where r' -> 0 and a naive dz = dr/r'
   * would blow up:
   *      dz = 2 r_w e^(u^2) du / sqrt(2K),   r(u) = r_w e^(u^2).
   * Simpson's rule on u is then well behaved.
   */
  function driftEnvelope(P, rw, rAnode, nSteps) {
    nSteps = nSteps || 80;
    var K = K_CONST * P;
    if (!(rAnode > rw) || !(K > 0)) return null;

    var uMax = Math.sqrt(Math.log(rAnode / rw));
    var scale = (2 * rw) / Math.sqrt(2 * K);
    var pts = [];
    var z = 0;
    var h = uMax / nSteps;

    for (var i = 0; i <= nSteps; i++) {
      var u = i * h;
      pts.push({ u: u, r: rw * Math.exp(u * u), z: 0 });
      if (i > 0) {
        // trapezoid on exp(t^2) over the last step; fine at this step count
        var a = Math.exp((u - h) * (u - h)), b = Math.exp(u * u);
        z += scale * 0.5 * (a + b) * h;
        pts[i].z = z;
      }
    }
    return { points: pts, length: z, uMax: uMax };
  }

  /*
   * Everything the drawing needs, in millimetres, with z = 0 at the cathode
   * surface on the axis and z increasing downstream toward the waist.
   */
  function geometry(opts) {
    var theta = opts.thetaDeg, rw = opts.rw, C = opts.C, P = opts.P;
    var table = opts.lbTable;

    var s = Math.sin(theta * deg);
    var rc = Math.sqrt(C) * rw;            // eq (2): cathode disc radius
    var Rc = s > 1e-9 ? rc / s : NaN;      // eq (4): radius of curvature

    var gamma = gammaFor(table, theta, P);
    var Ra = isFinite(gamma) ? Rc * Math.exp(-gamma) : NaN;
    var ra = isFinite(Ra) ? Ra * s : NaN;

    // Cathode cap sagitta: how far the dished cathode sits behind its rim.
    var sag = isFinite(Rc) ? Rc * (1 - Math.cos(theta * deg)) : NaN;
    // Along-axis distance from cathode pole to anode pole.
    var zAnode = isFinite(Ra) ? (Rc - Ra) : NaN;

    var drift = isFinite(ra) ? driftEnvelope(P, rw, ra) : null;

    /*
     * Say WHY when the geometry does not close. Both failures are real physics,
     * not glitches, and a reader dragging a slider deserves to know which wall
     * they hit rather than seeing the drawing blank out.
     */
    var reason = null;
    if (!isFinite(Rc)) {
      reason = "theta is too close to zero for R_c = r_c / sin(theta).";
    } else if (!isFinite(gamma)) {
      reason = "no gamma satisfies the Langmuir-Blodgett relation at this " +
               "perveance and angle: P = 29.33 (1 - cos theta) / alpha(gamma)^2 " +
               "has no solution in the tabulated range, which means this " +
               "combination of P and theta is not a physically realisable " +
               "space-charge-limited diode.";
    } else if (!drift) {
      reason = "the anode aperture radius r_a = " + ra.toFixed(2) + " mm is not " +
               "larger than the beam waist r_w = " + rw.toFixed(2) + " mm, so " +
               "there is no converging drift region to draw. At this low a " +
               "convergence ratio the beam barely narrows.";
    }

    return {
      reason: reason,
      thetaDeg: theta, P: P, rw: rw, C: C,
      rc: rc, Rc: Rc, gamma: gamma, Ra: Ra, ra: ra,
      sagitta: sag, zAnode: zAnode,
      drift: drift,
      zWaist: drift ? zAnode + drift.length : NaN,
      ok: isFinite(Rc) && isFinite(Ra) && !!drift,
    };
  }

  var api = {
    P_CONST: P_CONST, K_CONST: K_CONST,
    alphaOf: alphaOf, gammaFor: gammaFor,
    driftEnvelope: driftEnvelope, geometry: geometry,
  };

  root.EGUN = root.EGUN || {};
  root.EGUN.physics = api;
  if (typeof module !== "undefined" && module.exports) module.exports = api;
})(typeof globalThis !== "undefined" ? globalThis : this);
