"""
Tier B — synthetic rows from the validated physics, over a restricted envelope.

    python -m src.data.synth_generator --n 1000

WHAT THIS IS. A physics model, validated against a published table over a stated
envelope, evaluated at new points. That is the standard basis of surrogate
modelling. It is not experimental data, it is not extracted from a paper, and no
row it produces may ever be described as either.

WHY IT IS ALLOWED NOW (D9). D4 blocked synthetic generation because the model
missed its gate at MAE 1.66 deg / MRE 5.75 % over all 30 published cases, and
because of an arithmetic argument: a generator carrying more error than the
3.74 % target cannot train a surrogate to reach that target. Restricted to
C >= 8 the same model reaches MAE 0.85 deg / MRE 2.80 % (leave-one-out: 0.92 deg
/ 2.89 %), which is below 3.74 %, so the arithmetic objection no longer holds
there. It still holds everywhere else. **The strict gate is still failed.** See
reports/VALIDATION_table2.md and tests/test_physics_reproduces_table2.py.

THE C >= 8 FLOOR IS THE POINT, NOT A PARAMETER. Below it the model
under-predicts theta by a mean of -4.29 degrees. Widening the envelope silently
re-imports exactly the error the restriction exists to exclude.

ANCHORS, AND A DELIBERATE DEPARTURE FROM THE BRIEF
--------------------------------------------------
The brief asked for the real (P, rw, C) triples with C >= 8 to be included as
anchor points. All 23 of them qualify -- but **all seven of the paper's held-out
test guns have C >= 8**, so anchoring on all 23 would put the exact inputs of
every test gun into Tier B, and therefore into M3's training set. M3's score on
"held-out real guns" would then be measuring a model that had been trained at
those very coordinates. The M1-versus-M3 comparison is the entire point of
generating this data, and that would destroy it.

So anchors are drawn from the 16 real triples that are C >= 8 **and** in the
paper's training split. The seven test triples are excluded, and
`assert_no_test_leakage` below refuses to write a file that contains them.
"""

import argparse
import csv
import math
import os

import numpy as np
from scipy.stats import qmc

from ..ann import dataset as ds
from ..physics.probe_closure import solve_case

# --- the validated envelope. Do not widen C_MIN; see the module docstring. ---
C_LENS = 0.62            # aperture-lens coefficient, swept in VALIDATION_table2.md
P_RANGE = (0.30, 3.70)   # microperveance
RW_RANGE = (0.50, 4.50)  # mm
C_RANGE = (8.0, 320.0)   # dimensionless, sampled LOG-uniformly
THETA_RANGE = (9.0, 72.0)  # degrees; samples outside are rejected

# Measured accuracy of this generator over its envelope. Carried on every row.
GENERATOR_MRE_PCT = 2.80
GENERATOR_MAE_DEG = 0.85
GENERATOR_ENVELOPE = "C >= 8"

SOURCE_KEY = "project_physics_generator"
SOURCE_CITATION = (
    "Generated by this project's implementation of the classical Pierce synthesis "
    "physics. Validated against Panahi et al. 2025 Table 2 over the C >= 8 "
    "envelope: MAE 0.85 deg, MRE 2.80% across 23 published cases. "
    "NOT experimental data."
)

FIELDS = [
    "row_id", "tier", "source_key", "source_citation", "source_doi",
    "source_table", "source_case_id", "origin_refs", "origin_citations",
    "paper_split", "split", "perveance_uperv", "rw_mm", "C",
    "theta_cone_deg", "theta_source", "theta_ann_panahi_deg",
    "theta_iterative_deg", "theta_noniterative_deg", "theta_modified_noniter_deg",
    "beam_type", "rc_mm", "Rc_mm", "derived_fields",
    "generator_mre_pct", "generator_envelope", "orig_units", "notes",
]


def theta_for(P, rw, C):
    """The validated iterative method. NaN where no root exists."""
    return solve_case(P, rw, C, C_LENS)


def anchors():
    """
    Real operating points to pin the synthetic cloud to, from the TRAINING split
    only. See the module docstring for why the test guns are excluded.
    """
    path = os.path.join(ds.repo_root(), "data", "processed", "dataset_master.csv")
    with open(path, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    out = []
    for r in rows:
        C = float(r["C"])
        if C >= C_RANGE[0] and r["paper_split"] == "train":
            out.append((float(r["perveance_uperv"]), float(r["rw_mm"]), C,
                        int(r["source_case_id"])))
    return out


def test_triples():
    """(P, rw, C) of the held-out guns, which must never appear in Tier B."""
    path = os.path.join(ds.repo_root(), "data", "processed", "dataset_master.csv")
    with open(path, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    return {
        (round(float(r["perveance_uperv"]), 6), round(float(r["rw_mm"]), 6),
         round(float(r["C"]), 6))
        for r in rows if r["paper_split"] == "test"
    }


def sample(n, seed=0):
    """
    Scrambled Sobol over (P, rw, ln C).

    A low-discrepancy sequence rather than a uniform grid: a grid in three
    dimensions puts every sample on a shared lattice, so each variable is only
    ever seen at n^(1/3) distinct values and the network can learn the lattice
    instead of the physics. Sobol fills the box evenly at every scale and gives
    every sample a distinct coordinate in all three axes.

    C is sampled uniformly in ln C because the envelope spans a factor of 40 and
    because ln C is the coordinate the physics is written in -- the same argument
    as D8. Sampling C linearly would put three quarters of the rows above C = 80.
    """
    engine = qmc.Sobol(d=3, scramble=True, seed=seed)
    # Sobol is balanced at powers of two; ask for the next one up and trim.
    m = max(1, math.ceil(math.log2(max(n, 2))))
    u = engine.random_base2(m=m)

    P = P_RANGE[0] + u[:, 0] * (P_RANGE[1] - P_RANGE[0])
    rw = RW_RANGE[0] + u[:, 1] * (RW_RANGE[1] - RW_RANGE[0])
    lnC = math.log(C_RANGE[0]) + u[:, 2] * (math.log(C_RANGE[1]) - math.log(C_RANGE[0]))
    return np.column_stack([P, rw, np.exp(lnC)])


def generate(n, seed=0, verbose=True):
    """Returns (rows, stats). Rejection is reported, never silently absorbed."""
    kept, rejected_theta, unsolved = [], 0, 0

    anchor_pts = anchors()
    if verbose:
        print(f"  anchors: {len(anchor_pts)} real training-split triples with "
              f"C >= {C_RANGE[0]:g} (test-split triples deliberately excluded)")

    for P, rw, C, case in anchor_pts:
        th = theta_for(P, rw, C)
        if not np.isfinite(th):
            unsolved += 1
            continue
        if not (THETA_RANGE[0] <= th <= THETA_RANGE[1]):
            rejected_theta += 1
            continue
        kept.append((P, rw, C, th, f"anchor at the inputs of real case {case}"))

    # Draw in batches until n rows survive rejection.
    batch_seed = seed
    target = n
    while len(kept) < target:
        want = target - len(kept)
        pts = sample(max(want * 2, 64), seed=batch_seed)
        batch_seed += 1
        for P, rw, C in pts:
            if len(kept) >= target:
                break
            th = theta_for(P, rw, C)
            if not np.isfinite(th):
                unsolved += 1
                continue
            if not (THETA_RANGE[0] <= th <= THETA_RANGE[1]):
                rejected_theta += 1
                continue
            kept.append((P, rw, C, th, ""))

    stats = {
        "kept": len(kept),
        "anchors": len(anchor_pts),
        "rejected_theta_out_of_range": rejected_theta,
        "unsolved_no_root": unsolved,
    }
    return kept, stats


def to_records(kept):
    banned = test_triples()
    out = []
    for i, (P, rw, C, th, note) in enumerate(kept, start=1):
        key = (round(P, 6), round(rw, 6), round(C, 6))
        assert key not in banned, (
            f"generated row {key} matches a held-out test gun; refusing to write"
        )
        rc = math.sqrt(C) * rw
        Rc = rc / math.sin(math.radians(th))
        out.append({
            "row_id": f"SYN-{i:05d}",
            "tier": "B_synthetic",
            "source_key": SOURCE_KEY,
            "source_citation": SOURCE_CITATION,
            "source_doi": "",
            "source_table": "generated",
            "source_case_id": "",
            "origin_refs": "",
            "origin_citations": "",
            "paper_split": "",
            # Tier B is NEVER a test row. Testing a surrogate on its own
            # generator's output measures the generator, not the surrogate.
            "split": "train",
            "perveance_uperv": f"{P:.4f}",
            "rw_mm": f"{rw:.4f}",
            "C": f"{C:.4f}",
            "theta_cone_deg": f"{th:.4f}",
            # Explicit, per row, so no reader has to infer it from the tier.
            "theta_source": "physics_generator",
            "theta_ann_panahi_deg": "",
            "theta_iterative_deg": f"{th:.4f}",
            "theta_noniterative_deg": "",
            "theta_modified_noniter_deg": "",
            "beam_type": "pencil",
            "rc_mm": f"{rc:.4f}",
            "Rc_mm": f"{Rc:.4f}",
            "derived_fields": "theta_cone_deg;theta_iterative_deg;rc_mm;Rc_mm",
            "generator_mre_pct": f"{GENERATOR_MRE_PCT:.2f}",
            "generator_envelope": GENERATOR_ENVELOPE,
            "orig_units": "P in microperv; rw in mm; C dimensionless; angles in degrees",
            "notes": ("SYNTHETIC - physics model output, not a measurement. "
                      "Aperture-lens coefficient c=0.62. " + note).strip(),
        })
    return out


def main(argv=None):
    p = argparse.ArgumentParser(description="Generate Tier B synthetic rows.")
    p.add_argument("--n", type=int, default=1000,
                   help="rows to generate (default 1000; tested to 10000)")
    p.add_argument("--seed", type=int, default=20260918)
    p.add_argument("--out", default="data/processed/dataset_tier_b.csv")
    args = p.parse_args(argv)

    root = ds.repo_root()
    print(f"Tier B generation - envelope P {P_RANGE}, rw {RW_RANGE}, "
          f"C {C_RANGE} (log-uniform), theta {THETA_RANGE}")
    print(f"  generator validated at MAE {GENERATOR_MAE_DEG} deg / "
          f"MRE {GENERATOR_MRE_PCT} % over {GENERATOR_ENVELOPE}")
    print(f"  THE STRICT GATE IS STILL FAILED over the full envelope "
          f"(1.66 deg / 5.75 %) - see D9")

    kept, stats = generate(args.n, seed=args.seed)
    records = to_records(kept)

    path = args.out if os.path.isabs(args.out) else os.path.join(root, args.out)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS)
        w.writeheader()
        w.writerows(records)

    C = np.array([float(r["C"]) for r in records])
    th = np.array([float(r["theta_cone_deg"]) for r in records])
    print(f"\n  rows written           {stats['kept']}")
    print(f"    of which anchors     {stats['anchors']}")
    print(f"  rejected, theta range  {stats['rejected_theta_out_of_range']}")
    print(f"  rejected, no root      {stats['unsolved_no_root']}")
    print(f"  C     {C.min():.2f} .. {C.max():.2f}  (median {np.median(C):.2f})")
    print(f"  theta {th.min():.2f} .. {th.max():.2f} deg")
    print(f"  {path}")


if __name__ == "__main__":
    main()
